"use client";
import { useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDownToLine, BarChart3, MessageSquare, Table2 } from "lucide-react";
import { demoDestinations } from "@/data/demo-tourism";
import { reportServices, type VisitorReport } from "@/lib/visitor-reports";
const demand = [{month:"Sep",baseline:8900},{month:"Oct",baseline:12400},{month:"Nov",baseline:18230},{month:"Dec",baseline:16000},{month:"Jan",baseline:13000},{month:"Feb",baseline:11900}];
export function DashboardView({ reports = [], onRemoveReport }: { reports?: VisitorReport[]; onRemoveReport: (id:string)=>void }) {
  const [tab, setTab] = useState("demand");
  const [table, setTable] = useState(false);
  const [scenario, setScenario] = useState("baseline");
  const multiplier = scenario === "conservative" ? .8 : scenario === "high" ? 1.2 : 1;
  const forecast = demand.map((d,i)=>({...d,projected:Math.round(d.baseline*multiplier),range:[Math.round(d.baseline*multiplier*(.9-i*.02)),Math.round(d.baseline*multiplier*(1.1+i*.02))]}));
  const problems = reports.filter(r=>r.kind==="Problem");
  const appreciation = reports.filter(r=>r.kind==="Appreciation");
  const topService = reportServices.map(name=>({name,count:problems.filter(r=>r.service===name).length})).sort((a,b)=>b.count-a.count)[0];
  const exportData = () => {
    const csv = tab === "demand" ? 'Scenario,Month,Projected visits,Lower estimate,Upper estimate\n'+forecast.map(d=>`${scenario},${d.month},${d.projected},${d.range[0]},${d.range[1]}`).join('\n') : 'Service,Problems,Suggestions,Appreciations\n'+reportServices.map(s=>[s,...["Problem","Suggestion","Appreciation"].map(k=>reports.filter(r=>r.service===s&&r.kind===k).length)].join(',')).join('\n');
    const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`chinari-${tab}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  };
  return <div className="upgrade-page"><div className="section-heading"><div><span className="eyebrow">BHARATPUR · CITY INSIGHTS</span><h1>Better visits. Better decisions.</h1><p>Understand the season. Listen to visitors. Find what needs attention.</p></div><button className="action-green" onClick={exportData}><ArrowDownToLine size={16}/>Export {tab === "demand" ? "forecast" : "feedback"}</button></div>
    <div className="notice">Forecasts and visitor origins are illustrative estimates, not measured arrivals. Feedback totals reflect only reports saved in this browser.</div>
    <div className="insight-grid"><Metric label="Peak forecast" value={Math.max(...forecast.map(d=>d.projected)).toLocaleString()} note="November · selected scenario"/><Metric label="Local observations" value={String(reports.length)} note={`${problems.length} problems · ${reports.filter(r=>r.kind==="Suggestion").length} suggestions`}/><Metric label="Appreciations" value={String(appreciation.length)} note="Visitor feedback in this browser"/><Metric label="Needs a closer look" value={topService.count ? topService.name.split(' & ')[0] : "No reports"} note={topService.count ? `${topService.count} local problem reports` : "Share an observation to begin"}/></div>
    <div className="interest-chips" aria-label="Insight sections"><button className={tab==='demand'?'active':''} aria-pressed={tab==='demand'} onClick={()=>setTab('demand')}><BarChart3 size={16}/>Demand outlook</button><button className={tab==='feedback'?'active':''} aria-pressed={tab==='feedback'} onClick={()=>setTab('feedback')}><MessageSquare size={16}/>Visitor feedback</button></div>
    {tab==='demand' ? <><section className="insight-panel"><div className="section-heading"><div><h2>A view of the season ahead.</h2><p>Six-month forecast · September 2026 to February 2027</p></div><div className="flex flex-wrap gap-3"><select aria-label="Forecast scenario" className="planner-field" style={{width:'auto'}} value={scenario} onChange={e=>setScenario(e.target.value)}><option value="baseline">Baseline scenario</option><option value="conservative">Conservative (−20%)</option><option value="high">High demand (+20%)</option></select><button className="text-action" onClick={()=>setTable(!table)}><Table2 size={16}/>{table?'Show chart':'Show as table'}</button></div></div>
    {table ? <div className="overflow-x-auto"><table className="data-table"><caption className="sr-only">Illustrative demand forecast</caption><thead><tr><th>Month</th><th>Projected visits</th><th>Scenario range</th></tr></thead><tbody>{forecast.map(d=><tr key={d.month}><td>{d.month}</td><td>{d.projected.toLocaleString()}</td><td>{d.range.map(v=>v.toLocaleString()).join(' – ')}</td></tr>)}</tbody></table></div> : <div style={{height:310,width:'100%'}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={forecast} margin={{top:20,right:15,left:0,bottom:5}}><CartesianGrid strokeDasharray="4 5" vertical={false} stroke="#e6e9df"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:11,fill:'#74816e'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:11,fill:'#74816e'}} tickFormatter={v=>`${v/1000}k`}/><Tooltip contentStyle={{borderRadius:12,border:'1px solid #d8e1d0'}}/><Area dataKey="range" name="Scenario range" stroke="none" fill="#ead0ba" fillOpacity={.55}/><Area type="monotone" dataKey="projected" name="Projected visits" stroke="#b9683e" strokeWidth={3} fill="#c77b4c" fillOpacity={.08}/></AreaChart></ResponsiveContainer></div>}
    <p className="small-note mt-4">Model: illustrative monthly baseline × scenario multiplier. The range widens by 2 percentage points each month; it is an assumed scenario band, not a statistical confidence interval.</p></section>
    <div className="insight-columns"><section className="insight-panel"><h2>Where visitors might come from.</h2><p className="small-note">Illustrative visitor mix.</p>{[{name:'Domestic · Nepal',value:61.4,note:'1.4 nights · NPR 3,200/day modelled spend'},{name:'India',value:24.8,note:'2.1 nights · NPR 5,400/day modelled spend'},{name:'Other international',value:13.8,note:'3.3 nights · NPR 11,800/day modelled spend'}].map(d=><div key={d.name} className="mt-5"><div className="flex justify-between text-sm"><strong>{d.name}</strong><span>{d.value}%</span></div><div className="progress-track"><span style={{width:`${d.value}%`}}/></div><p className="small-note -mt-3">{d.note}</p></div>)}</section><section className="insight-panel"><h2>Make room for the less discovered.</h2><p className="small-note">Curated hidden gems · relative discovery score.</p>{demoDestinations.filter(d=>d.hidden_gem).map(d=><div key={d.id} className="mt-5"><div className="flex justify-between gap-3 text-sm"><strong>{d.name}</strong><span>{d.popularity}/100</span></div><div className="progress-track"><span style={{width:`${d.popularity}%`}}/></div></div>)}</section></div></> : <>
    <section className="insight-panel"><h2>What visitors are telling us.</h2><p className="small-note">Counts from local reports, grouped by the visitor’s selected category.</p><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Service</th><th>Problems</th><th>Suggestions</th><th>Appreciations</th></tr></thead><tbody>{reportServices.map(s=><tr key={s}><td>{s}</td>{['Problem','Suggestion','Appreciation'].map(k=><td key={k}>{reports.filter(r=>r.service===s&&r.kind===k).length}</td>)}</tr>)}</tbody></table></div></section>
    <section className="insight-panel mt-5"><h2>Recent local observations</h2>{!reports.length?<p className="small-note">No observations yet. Use Report in the navigation to add one.</p>:reports.slice().reverse().slice(0,10).map(r=><article key={r.id} className="border-t border-[#e3e8dc] py-4 mt-3"><div className="flex flex-wrap justify-between gap-3 text-xs"><strong>{r.kind} · {r.service}</strong><span>{r.ward==='Unconfirmed'?'Ward unconfirmed':`Ward ${r.ward}`} · {new Date(r.createdAt).toLocaleDateString()}</span></div><p className="mt-3 text-sm leading-6 whitespace-pre-wrap break-words">{r.message}</p><div className="mt-2 flex items-center justify-between"><p className="small-note">Local report · {r.id.slice(0,8)}</p><button onClick={()=>onRemoveReport(r.id)} className="text-xs text-[#a45138]">Remove local report</button></div></article>)}</section></>}
    <section className="insight-panel mt-5"><h2>What still needs checking.</h2><p className="small-note">Verification status of the {demoDestinations.length} curated discovery listings.</p>{(['VERIFIED','UNVERIFIED','DEMO'] as const).map(status=>{const count=demoDestinations.filter(d=>d.verification_status===status).length;return <div key={status} className="mt-4"><div className="flex justify-between text-xs"><strong>{status==='VERIFIED'?'Source verified':status==='UNVERIFIED'?'Needs local verification':'Directory entry'}</strong><span>{count} / {demoDestinations.length}</span></div><div className="progress-track"><span style={{width:`${count/demoDestinations.length*100}%`,background:status==='VERIFIED'?'#2a6046':status==='UNVERIFIED'?'#bc8b3d':'#b96949'}}/></div></div>;})}</section>
  </div>;
}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className="metric-tile"><small>{label}</small><strong>{value}</strong><p>{note}</p></div>;}
