"use client";

import { Download, ArrowDown, ArrowUp, Clock3, MapPin, Navigation, Route, Sparkles, Trash2, WandSparkles } from "lucide-react";
import type { Destination, ItineraryItem, PlannerPreferences } from "@/types/tourism";
import { LeafletMap } from "./leaflet-map";

export function JourneyView({ preferences, itinerary, selected, onOptimize, onMove, onRemove, onPlanner, onOpen }: { preferences: PlannerPreferences; itinerary: ItineraryItem[]; selected: Destination[]; onOptimize: () => void; onMove: (index: number, direction: -1 | 1) => void; onRemove: (id: string) => void; onPlanner: () => void; onOpen: (destination: Destination) => void }) {
  const dateForDay = (day: number) => { if(!preferences.startDate) return `Day ${day}`;const date = new Date(`${preferences.startDate}T12:00:00`);date.setDate(date.getDate()+day-1);return `Day ${day} · ${date.toLocaleDateString(undefined,{month:"short",day:"numeric"})}`; };
  const exportJourney = () => { const text = ["CHINARI · YOUR JOURNEY", "Planning estimates; confirm access, travel times and prices locally.", `Transport: ${preferences.transport} · Pace: ${preferences.pace ?? "balanced"} · Daily budget preference: NPR ${preferences.dailyBudget ?? 4000}`, ...itinerary.map(item=>`\n${dateForDay(item.day)} · ${item.arrival} · ${item.destination.name}\nVisit: ${item.destination.estimated_duration} · Transfer estimate: ${item.travel_minutes} min\n${item.destination.safety_information}`)].join("\n");const url=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="chinari-journey.txt";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000); };
  if (!selected.length) return <div className="mx-auto grid min-h-[70vh] max-w-3xl place-items-center px-5 text-center"><div><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#e4eadf]"><Route size={28}/></span><h1 className="mt-6 font-serif text-5xl">Your journey starts with a place.</h1><p className="mx-auto mt-4 max-w-xl text-lg leading-8 text-[#68776d]">Choose destinations from Explore or let Chinari shape a day around your time, budget and interests.</p><button onClick={onPlanner} className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#c45b2f] px-6 font-bold text-white"><Sparkles size={18}/>Plan my trip</button></div></div>;
  const ordered = itinerary.length ? itinerary.map((item) => item.destination) : selected;
  return (
    <div className="mx-auto max-w-[1600px] px-4 pb-24 pt-6 sm:px-6 lg:px-8">
      <div className="mb-6 flex flex-wrap items-end justify-between gap-4 px-1"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#c45b2f]">Smart journey</p><h1 className="mt-2 font-serif text-5xl">Your time, thoughtfully spent.</h1></div><div className="flex flex-wrap gap-2"><button onClick={exportJourney} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#1f4d3a]/16 px-4 text-sm font-bold"><Download size={16}/>Save itinerary</button><button onClick={onPlanner} className="min-h-11 rounded-full border border-[#1f4d3a]/16 px-4 text-sm font-bold">Edit preferences</button><button onClick={onOptimize} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#15382a] px-5 text-sm font-bold text-white"><WandSparkles size={17}/>Optimize again</button></div></div>
      <div className="mb-5 rounded-2xl bg-[#eaf0e7] p-4 text-sm leading-7">{Math.max(1,...itinerary.map(item=>item.day))} day(s) · {preferences.pace ?? "balanced"} pace · {preferences.transport} · NPR {(preferences.dailyBudget ?? 4000).toLocaleString()}/day preference<br/><span className="small-note">Travel times use straight-line estimates. Each day starts in central Bharatpur; meals, return transfers, opening hours and lodging need local confirmation. Budget is a preference, not a quoted trip cost.</span></div>
      <div className="grid min-h-[720px] overflow-hidden rounded-[34px] border border-[#1f4d3a]/10 bg-white shadow-[0_24px_60px_rgba(33,63,45,.12)] lg:grid-cols-[520px_1fr]">
        <div className="order-1 overflow-y-auto p-4 sm:p-6 lg:max-h-[760px]">
          <div className="mb-5 rounded-[22px] bg-[#eef1e9] p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#c45b2f] text-white"><Navigation size={18}/></span><div><p className="font-bold">Start: Central Bharatpur</p><p className="text-sm text-[#68776d]">Daily starting point · estimated transfers</p></div></div></div>
          <ol className="space-y-1">{itinerary.map((item, index) => <li key={item.destination.id}>{(index===0 || itinerary[index-1].day!==item.day) && <h2 className="mb-3 mt-5 text-sm font-bold text-[#b46640]">{dateForDay(item.day)} · {item.travel_minutes} min from central Bharatpur</h2>}<div className="relative rounded-[24px] border border-[#1f4d3a]/10 p-4 transition hover:bg-[#faf8f1]"><div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#15382a] font-serif text-lg text-white">{String(index + 1).padStart(2, "0")}</span><button onClick={() => onOpen(item.destination)} className="min-w-0 flex-1 text-left"><p className="text-xs font-bold uppercase tracking-wider text-[#c45b2f]">{item.arrival}</p><h2 className="mt-1 truncate font-serif text-2xl">{item.destination.name}</h2><p className="mt-1 text-sm text-[#68776d]">{item.reason}</p><div className="mt-3 flex flex-wrap gap-3 text-xs font-semibold text-[#68776d]"><span className="inline-flex items-center gap-1"><Clock3 size={13}/>{item.destination.estimated_duration}</span><span className="inline-flex items-center gap-1"><MapPin size={13}/>{item.destination.category}</span></div></button><div className="flex shrink-0 flex-col gap-1"><button onClick={() => onMove(index, -1)} disabled={index === 0} className="grid h-8 w-8 place-items-center rounded-full bg-[#edf1e9] disabled:opacity-30" aria-label="Move earlier"><ArrowUp size={14}/></button><button onClick={() => onMove(index, 1)} disabled={index === itinerary.length - 1} className="grid h-8 w-8 place-items-center rounded-full bg-[#edf1e9] disabled:opacity-30" aria-label="Move later"><ArrowDown size={14}/></button><button onClick={() => onRemove(item.destination.id)} className="grid h-8 w-8 place-items-center rounded-full bg-red-50 text-red-700" aria-label="Remove"><Trash2 size={14}/></button></div></div></div>{index < itinerary.length - 1 && itinerary[index+1].day===item.day && <div className="ml-[37px] border-l-2 border-dashed border-[#c45b2f]/45 py-3 pl-8 text-xs font-bold text-[#8b6a59]">{itinerary[index + 1].travel_minutes} min · {itinerary[index + 1].distance_km} km</div>}</li>)}</ol>
        </div>
        <div className="order-2 min-h-[420px] bg-[#dce5d9]"><LeafletMap destinations={ordered} selectedIds={ordered.map((item) => item.id)} numbered onSelect={onOpen} className="min-h-[420px] lg:min-h-[760px]"/></div>
      </div>
    </div>
  );
}
